version: '3'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Eploy-service
    ports:
      - "8088:8088"
    tty: true
    volumes:
      - .:/go/src/app
    networks:
          - eploy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 13307:3306
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - eploy
        
networks:
    eploy:
     external: true